In [1]:
import yfinance as yf

# Load stock data

In [90]:
x = yf.Ticker("QQQ")

In [91]:
df = x.history(interval="1h", period="730d", keepna=True)
df.drop(columns=["Dividends", "Stock Splits", "Capital Gains"], inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 5092 entries, 2022-08-01 09:30:00-04:00 to 2025-06-27 15:30:00-04:00
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Open    5086 non-null   float64
 1   High    5086 non-null   float64
 2   Low     5086 non-null   float64
 3   Close   5086 non-null   float64
 4   Volume  5092 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 238.7 KB

# Impute missing values

In [92]:
df[df.isna().any(axis=1)]

                           Open  High  Low  Close  Volume
Datetime
2022-11-25 12:30:00-05:00   NaN   NaN  NaN    NaN       0
2023-07-03 12:30:00-04:00   NaN   NaN  NaN    NaN       0
2023-11-24 12:30:00-05:00   NaN   NaN  NaN    NaN       0
2024-07-03 12:30:00-04:00   NaN   NaN  NaN    NaN       0
2024-11-29 12:30:00-05:00   NaN   NaN  NaN    NaN       0
2024-12-24 12:30:00-05:00   NaN   NaN  NaN    NaN       0

In [93]:
df["Close"] = df["Close"].ffill()
df.fillna(
    {
        "Open": df["Close"],
        "High": df["Close"],
        "Low": df["Close"],
    },
    inplace=True,
)
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 5092 entries, 2022-08-01 09:30:00-04:00 to 2025-06-27 15:30:00-04:00
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Open    5092 non-null   float64
 1   High    5092 non-null   float64
 2   Low     5092 non-null   float64
 3   Close   5092 non-null   float64
 4   Volume  5092 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 238.7 KB

# Add time series features

In [157]:
import pandas as pd

df['delta_time'] = df.index.to_series().diff().dt.total_seconds() / 60
df['delta_time'] = df['delta_time'].fillna(0).astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 5092 entries, 2022-08-01 09:30:00-04:00 to 2025-06-27 15:30:00-04:00
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Open        5092 non-null   float64
 1   High        5092 non-null   float64
 2   Low         5092 non-null   float64
 3   Close       5092 non-null   float64
 4   Volume      5092 non-null   int64
 5   delta_time  5092 non-null   int64
dtypes: float64(4), int64(2)
memory usage: 407.5 KB

In [158]:
df.head(40)

,Open,High,Low,Close,Volume,delta_time
Datetime,,,,,,
2022-08-01 09:30:00-04:00,313.915009,317.799988,312.529999,315.739990,13848875,0
2022-08-01 10:30:00-04:00,315.769989,318.809998,315.100006,317.950012,7057038,60
2022-08-01 11:30:00-04:00,317.959991,318.420013,316.309998,317.000092,4346872,60
2022-08-01 12:30:00-04:00,317.000000,317.098999,314.630005,314.660004,4451567,60
2022-08-01 13:30:00-04:00,314.665497,315.390015,313.690002,314.910004,5137698,60
2022-08-01 14:30:00-04:00,314.929993,316.179993,314.589996,314.869995,4498435,60
2022-08-01 15:30:00-04:00,314.869995,315.839996,314.779999,315.239990,5045600,60
2022-08-02 09:30:00-04:00,312.899994,315.100006,311.840088,313.910004,12999088,1080
2022-08-02 10:30:00-04:00,313.910004,316.239990,313.250000,315.399994,6646904,60
2022-08-02 11:30:00-04:00,315.380005,318.130005,314.291595,318.019989,5832569,60
2022-08-02 12:30:00-04:00,318.019989,318.545013,315.799988,315.950012,4408560,60
2022-08-02 13:30:00-04:00,315.950012,315.950012,313.850006,315.649994,6679815,60
2022-08-02 14:30:00-04:00,315.660004,316.200012,314.309998,315.230011,5389682,60
2022-08-02 15:30:00-04:00,315.250000,315.700012,314.239990,314.290009,4252610,60
2022-08-03 09:30:00-04:00,316.859985,320.420013,316.720001,319.353790,14682427,1080
2022-08-03 10:30:00-04:00,319.350006,320.859985,317.695007,320.609985,7425975,60
2022-08-03 11:30:00-04:00,320.609985,321.670013,320.309998,321.269989,5552797,60
2022-08-03 12:30:00-04:00,321.270111,322.970001,321.239990,322.709991,5249145,60
2022-08-03 13:30:00-04:00,322.720001,323.369995,322.279999,323.040009,4288893,60
2022-08-03 14:30:00-04:00,323.040009,323.420013,322.589996,322.820007,4774187,60
2022-08-03 15:30:00-04:00,322.820007,323.729095,322.679993,322.809998,8599276,60
2022-08-04 09:30:00-04:00,322.750000,324.519989,321.911896,322.130005,12061112,1080
2022-08-04 10:30:00-04:00,322.130005,322.790009,320.769989,321.720001,6667541,60
2022-08-04 11:30:00-04:00,321.700012,323.926086,321.230011,323.809998,3968795,60
2022-08-04 12:30:00-04:00,323.810089,323.811890,322.209991,323.619995,3508734,60
2022-08-04 13:30:00-04:00,323.600006,323.980011,322.885010,323.600098,2637682,60
2022-08-04 14:30:00-04:00,323.626709,324.720001,323.069092,324.359985,3555131,60
2022-08-04 15:30:00-04:00,324.369995,324.399994,323.369995,324.325012,4307639,60
2022-08-05 09:30:00-04:00,319.190002,323.829987,319.089996,322.959991,17652699,1080
2022-08-05 10:30:00-04:00,322.959991,323.029907,318.510010,318.511505,7592274,60
2022-08-05 11:30:00-04:00,318.519989,320.489990,318.390015,320.380005,7524594,60
2022-08-05 12:30:00-04:00,320.380005,322.119995,319.500000,321.470001,4957558,60
2022-08-05 13:30:00-04:00,321.484985,322.178986,320.059998,320.070007,3893586,60
2022-08-05 14:30:00-04:00,320.070007,320.940002,319.839996,320.880005,4254318,60
2022-08-05 15:30:00-04:00,320.869995,322.049988,320.730988,321.790009,4670541,60
2022-08-08 09:30:00-04:00,322.690002,326.470001,321.910004,324.950012,13912704,3960
2022-08-08 10:30:00-04:00,324.980011,325.679993,323.059998,323.179993,5375634,60
2022-08-08 11:30:00-04:00,323.170013,323.614990,320.170013,320.480011,7278537,60
2022-08-08 12:30:00-04:00,320.450012,321.934998,320.140015,320.869995,4406893,60
2022-08-08 13:30:00-04:00,320.880005,321.529999,319.730011,320.149994,3833433,60

In [112]:
df['delta_time'].max()

np.float64(5400.0)

In [113]:
df[df['delta_time'] == 5400]

,Open,High,Low,Close,Volume,delta_time
Datetime,,,,,,
2022-09-06 09:30:00-04:00,295.660004,296.600006,290.869995,292.410004,13946782,5400.0
2022-12-27 09:30:00-05:00,266.739990,266.850006,263.029999,265.239990,9805924,5400.0
2023-01-03 09:30:00-05:00,268.649994,270.154999,264.019989,264.579987,11749638,5400.0
2023-01-17 09:30:00-05:00,280.987610,282.850006,279.580994,282.200012,11354974,5400.0
2023-02-21 09:30:00-05:00,297.500000,298.730011,296.109985,296.239990,13338107,5400.0
2023-04-10 09:30:00-04:00,315.070007,315.239990,313.250000,313.860107,12243821,5400.0
2023-05-30 09:30:00-04:00,352.670013,353.929993,350.059998,350.700012,24991472,5400.0
2023-06-20 09:30:00-04:00,366.179993,368.320007,363.980011,364.249908,12438771,5400.0
2023-09-05 09:30:00-04:00,376.769989,377.769989,375.829987,376.959991,8513504,5400.0
2023-12-26 09:30:00-05:00,409.250000,410.320007,409.149994,410.010010,4601366,5400.0
2024-01-02 09:30:00-05:00,406.000000,406.089996,402.480011,402.640106,15887112,5400.0
2024-01-16 09:30:00-05:00,408.625000,410.380005,406.829987,410.109985,12620883,5400.0
2024-02-20 09:30:00-05:00,428.929993,430.079987,424.720001,424.850006,13779668,5400.0
2024-04-01 09:30:00-04:00,444.959991,447.529999,444.549988,445.819885,10434848,5400.0
2024-05-28 09:30:00-04:00,459.149994,459.559998,457.100006,458.529999,5743068,5400.0
2024-09-03 09:30:00-04:00,473.170013,473.299988,468.489990,469.309998,9774336,5400.0
2025-01-21 09:30:00-05:00,524.489990,524.690002,520.059998,522.830017,6389723,5400.0
2025-02-18 09:30:00-05:00,539.770020,540.000000,536.694824,536.890015,5384886,5400.0
2025-04-21 09:30:00-04:00,438.359985,439.079987,432.649994,433.320007,8320692,5400.0
2025-05-27 09:30:00-04:00,516.159973,519.169983,514.590027,518.849976,12094472,5400.0

In [135]:
x = df.index.get_loc("2025-05-27 09:30:00-04:00")
df.iloc[x - 1], df.iloc[x], df.iloc[x + 1]

(Open          5.101500e+02
 High          5.111045e+02
 Low           5.088200e+02
 Close         5.092865e+02
 Volume        6.856161e+06
 delta_time    6.000000e+01
 Name: 2025-05-23 15:30:00-04:00, dtype: float64,
 Open          5.161600e+02
 High          5.191700e+02
 Low           5.145900e+02
 Close         5.188500e+02
 Volume        1.209447e+07
 delta_time    5.400000e+03
 Name: 2025-05-27 09:30:00-04:00, dtype: float64,
 Open          5.188600e+02
 High          5.195750e+02
 Low           5.183500e+02
 Close         5.193400e+02
 Volume        5.405546e+06
 delta_time    6.000000e+01
 Name: 2025-05-27 10:30:00-04:00, dtype: float64)

In [144]:
df[df['delta_time'] != 60]['delta_time'].value_counts()

delta_time
1080.0    568
3960.0    122
5400.0     20
2520.0      7
4020.0      3
4140.0      3
3900.0      3
2700.0      3
Name: count, dtype: int64

In [147]:
df[df['delta_time'] == 1080]

,Open,High,Low,Close,Volume,delta_time
Datetime,,,,,,
2022-08-02 09:30:00-04:00,312.899994,315.100006,311.840088,313.910004,12999088,1080.0
2022-08-03 09:30:00-04:00,316.859985,320.420013,316.720001,319.353790,14682427,1080.0
2022-08-04 09:30:00-04:00,322.750000,324.519989,321.911896,322.130005,12061112,1080.0
2022-08-05 09:30:00-04:00,319.190002,323.829987,319.089996,322.959991,17652699,1080.0
2022-08-09 09:30:00-04:00,318.769989,319.029999,315.649994,316.939911,11400215,1080.0
...,...,...,...,...,...,...
2025-06-18 09:30:00-04:00,530.080017,532.179993,528.479980,531.979980,8881047,1080.0
2025-06-24 09:30:00-04:00,536.700012,538.039978,536.271973,537.405029,10883870,1080.0
2025-06-25 09:30:00-04:00,542.150024,543.309998,541.250000,541.789978,13109829,1080.0
2025-06-26 09:30:00-04:00,543.419983,543.864990,541.520020,543.781006,10024511,1080.0
2025-06-27 09:30:00-04:00,547.200012,549.979980,546.739990,549.025208,10170395,1080.0

# Add indicators and signals

In [ ]:
from ta import add_all_ta_features

In [94]:
df

,Open,High,Low,Close,Volume
Datetime,,,,,
2022-08-01 09:30:00-04:00,313.915009,317.799988,312.529999,315.739990,13848875
2022-08-01 10:30:00-04:00,315.769989,318.809998,315.100006,317.950012,7057038
2022-08-01 11:30:00-04:00,317.959991,318.420013,316.309998,317.000092,4346872
2022-08-01 12:30:00-04:00,317.000000,317.098999,314.630005,314.660004,4451567
2022-08-01 13:30:00-04:00,314.665497,315.390015,313.690002,314.910004,5137698
...,...,...,...,...,...
2025-06-27 11:30:00-04:00,549.260010,549.929871,548.919983,549.359985,4974769
2025-06-27 12:30:00-04:00,549.369995,549.429321,548.609985,548.760010,6454192
2025-06-27 13:30:00-04:00,548.739990,548.989929,546.179993,546.179993,9088471
2025-06-27 14:30:00-04:00,546.190002,546.609985,544.544983,546.260010,9399330
2025-06-27 15:30:00-04:00,546.299988,548.385010,546.289978,548.219971,8241611

In [71]:
df_wInd = df.copy()
df_wInd = add_all_ta_features(
    df_wInd,
    open="Open",
    high="High",
    low="Low",
    close="Close",
    volume="Volume",
    fillna=False,
)
df_wInd.drop(
    columns=[
        "volume_em",
        "volume_sma_em",
        "trend_psar_up",
        "trend_psar_down",
        "trend_psar_up_indicator",
        "trend_psar_down_indicator",
    ],
    inplace=True,
)
df_wInd.info()

/Users/hetpatel/Documents/Python Projects/AI/BigBrainTrader/.venv/lib/python3.9/site-packages/ta/trend.py:1030: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  self._psar[i] = high2

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 5092 entries, 2022-08-01 09:30:00-04:00 to 2025-06-27 15:30:00-04:00
Data columns (total 85 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Open                     5092 non-null   float64
 1   High                     5092 non-null   float64
 2   Low                      5092 non-null   float64
 3   Close                    5092 non-null   float64
 4   Volume                   5092 non-null   int64
 5   volume_adi               5092 non-null   float64
 6   volume_obv               5092 non-null   int64
 7   volume_cmf               5073 non-null   float64
 8   volume_fi                5079 non-null   float64
 9   volume_vpt               5091 non-null   float64
 10  volume_vwap              5079 non-null   float64
 11  volume_mfi               5079 non-null   float64
 12  volume_nvi               5092 non-null   float64
 13  volatility_bbm           5073 non-null   float64
 14  volatility_bbh           5073 non-null   float64
 15  volatility_bbl           5073 non-null   float64
 16  volatility_bbw           5073 non-null   float64
 17  volatility_bbp           5073 non-null   float64
 18  volatility_bbhi          5092 non-null   float64
 19  volatility_bbli          5092 non-null   float64
 20  volatility_kcc           5083 non-null   float64
 21  volatility_kch           5092 non-null   float64
 22  volatility_kcl           5092 non-null   float64
 23  volatility_kcw           5083 non-null   float64
 24  volatility_kcp           5092 non-null   float64
 25  volatility_kchi          5092 non-null   float64
 26  volatility_kcli          5092 non-null   float64
 27  volatility_dcl           5073 non-null   float64
 28  volatility_dch           5073 non-null   float64
 29  volatility_dcm           5073 non-null   float64
 30  volatility_dcw           5073 non-null   float64
 31  volatility_dcp           5073 non-null   float64
 32  volatility_atr           5092 non-null   float64
 33  volatility_ui            5079 non-null   float64
 34  trend_macd               5067 non-null   float64
 35  trend_macd_signal        5059 non-null   float64
 36  trend_macd_diff          5059 non-null   float64
 37  trend_sma_fast           5081 non-null   float64
 38  trend_sma_slow           5067 non-null   float64
 39  trend_ema_fast           5081 non-null   float64
 40  trend_ema_slow           5067 non-null   float64
 41  trend_vortex_ind_pos     5078 non-null   float64
 42  trend_vortex_ind_neg     5078 non-null   float64
 43  trend_vortex_ind_diff    5078 non-null   float64
 44  trend_trix               5049 non-null   float64
 45  trend_mass_index         5052 non-null   float64
 46  trend_dpo                5073 non-null   float64
 47  trend_kst                5078 non-null   float64
 48  trend_kst_sig            5078 non-null   float64
 49  trend_kst_diff           5078 non-null   float64
 50  trend_ichimoku_conv      5084 non-null   float64
 51  trend_ichimoku_base      5067 non-null   float64
 52  trend_ichimoku_a         5067 non-null   float64
 53  trend_ichimoku_b         5092 non-null   float64
 54  trend_stc                5021 non-null   float64
 55  trend_adx                5092 non-null   float64
 56  trend_adx_pos            5092 non-null   float64
 57  trend_adx_neg            5092 non-null   float64
 58  trend_cci                5073 non-null   float64
 59  trend_visual_ichimoku_a  5067 non-null   float64
 60  trend_visual_ichimoku_b  5092 non-null   float64
 61  trend_aroon_up           5067 non-null   float64
 62  trend_aroon_down         5067 non-null   float64
 63  trend_aroon_ind          5067 non-null   float64
 64  momentum_rsi             5079 non-null   float64
 65  momentum_stoch_rsi       5066 non-null   float64
 66  momentum_stoch_rsi_k     5064 non-null   float64
 67  momentum_stoch_rsi_d     5062 non-null   float64
 68  momentum_tsi             5055 non-null   float64
 69  momentum_uo              5064 non-null   float64
 70  momentum_stoch           5079 non-null   float64
 71  momentum_stoch_signal    5077 non-null   float64
 72  momentum_wr              5079 non-null   float64
 73  momentum_ao              5059 non-null   float64
 74  momentum_roc             5080 non-null   float64
 75  momentum_ppo             5067 non-null   float64
 76  momentum_ppo_signal      5059 non-null   float64
 77  momentum_ppo_hist        5059 non-null   float64
 78  momentum_pvo             5067 non-null   float64
 79  momentum_pvo_signal      5059 non-null   float64
 80  momentum_pvo_hist        5059 non-null   float64
 81  momentum_kama            5083 non-null   float64
 82  others_dr                5091 non-null   float64
 83  others_dlr               5091 non-null   float64
 84  others_cr                5092 non-null   float64
dtypes: float64(83), int64(2)
memory usage: 3.3 MB

In [72]:
df_filtered = df_wInd.loc["2022-08-17 09:30:00-04:00":]
df_filtered.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 5008 entries, 2022-08-17 09:30:00-04:00 to 2025-06-27 15:30:00-04:00
Data columns (total 85 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Open                     5008 non-null   float64
 1   High                     5008 non-null   float64
 2   Low                      5008 non-null   float64
 3   Close                    5008 non-null   float64
 4   Volume                   5008 non-null   int64
 5   volume_adi               5008 non-null   float64
 6   volume_obv               5008 non-null   int64
 7   volume_cmf               5008 non-null   float64
 8   volume_fi                5008 non-null   float64
 9   volume_vpt               5008 non-null   float64
 10  volume_vwap              5008 non-null   float64
 11  volume_mfi               5008 non-null   float64
 12  volume_nvi               5008 non-null   float64
 13  volatility_bbm           5008 non-null   float64
 14  volatility_bbh           5008 non-null   float64
 15  volatility_bbl           5008 non-null   float64
 16  volatility_bbw           5008 non-null   float64
 17  volatility_bbp           5008 non-null   float64
 18  volatility_bbhi          5008 non-null   float64
 19  volatility_bbli          5008 non-null   float64
 20  volatility_kcc           5008 non-null   float64
 21  volatility_kch           5008 non-null   float64
 22  volatility_kcl           5008 non-null   float64
 23  volatility_kcw           5008 non-null   float64
 24  volatility_kcp           5008 non-null   float64
 25  volatility_kchi          5008 non-null   float64
 26  volatility_kcli          5008 non-null   float64
 27  volatility_dcl           5008 non-null   float64
 28  volatility_dch           5008 non-null   float64
 29  volatility_dcm           5008 non-null   float64
 30  volatility_dcw           5008 non-null   float64
 31  volatility_dcp           5008 non-null   float64
 32  volatility_atr           5008 non-null   float64
 33  volatility_ui            5008 non-null   float64
 34  trend_macd               5008 non-null   float64
 35  trend_macd_signal        5008 non-null   float64
 36  trend_macd_diff          5008 non-null   float64
 37  trend_sma_fast           5008 non-null   float64
 38  trend_sma_slow           5008 non-null   float64
 39  trend_ema_fast           5008 non-null   float64
 40  trend_ema_slow           5008 non-null   float64
 41  trend_vortex_ind_pos     5008 non-null   float64
 42  trend_vortex_ind_neg     5008 non-null   float64
 43  trend_vortex_ind_diff    5008 non-null   float64
 44  trend_trix               5008 non-null   float64
 45  trend_mass_index         5008 non-null   float64
 46  trend_dpo                5008 non-null   float64
 47  trend_kst                5008 non-null   float64
 48  trend_kst_sig            5008 non-null   float64
 49  trend_kst_diff           5008 non-null   float64
 50  trend_ichimoku_conv      5008 non-null   float64
 51  trend_ichimoku_base      5008 non-null   float64
 52  trend_ichimoku_a         5008 non-null   float64
 53  trend_ichimoku_b         5008 non-null   float64
 54  trend_stc                5008 non-null   float64
 55  trend_adx                5008 non-null   float64
 56  trend_adx_pos            5008 non-null   float64
 57  trend_adx_neg            5008 non-null   float64
 58  trend_cci                5008 non-null   float64
 59  trend_visual_ichimoku_a  5008 non-null   float64
 60  trend_visual_ichimoku_b  5008 non-null   float64
 61  trend_aroon_up           5008 non-null   float64
 62  trend_aroon_down         5008 non-null   float64
 63  trend_aroon_ind          5008 non-null   float64
 64  momentum_rsi             5008 non-null   float64
 65  momentum_stoch_rsi       5008 non-null   float64
 66  momentum_stoch_rsi_k     5008 non-null   float64
 67  momentum_stoch_rsi_d     5008 non-null   float64
 68  momentum_tsi             5008 non-null   float64
 69  momentum_uo              5008 non-null   float64
 70  momentum_stoch           5008 non-null   float64
 71  momentum_stoch_signal    5008 non-null   float64
 72  momentum_wr              5008 non-null   float64
 73  momentum_ao              5008 non-null   float64
 74  momentum_roc             5008 non-null   float64
 75  momentum_ppo             5008 non-null   float64
 76  momentum_ppo_signal      5008 non-null   float64
 77  momentum_ppo_hist        5008 non-null   float64
 78  momentum_pvo             5008 non-null   float64
 79  momentum_pvo_signal      5008 non-null   float64
 80  momentum_pvo_hist        5008 non-null   float64
 81  momentum_kama            5008 non-null   float64
 82  others_dr                5008 non-null   float64
 83  others_dlr               5008 non-null   float64
 84  others_cr                5008 non-null   float64
dtypes: float64(83), int64(2)
memory usage: 3.3 MB

In [73]:
df_filtered[df_filtered.isna().any(axis=1)]

Empty DataFrame
Columns: [Open, High, Low, Close, Volume, volume_adi, volume_obv, volume_cmf, volume_fi, volume_vpt, volume_vwap, volume_mfi, volume_nvi, volatility_bbm, volatility_bbh, volatility_bbl, volatility_bbw, volatility_bbp, volatility_bbhi, volatility_bbli, volatility_kcc, volatility_kch, volatility_kcl, volatility_kcw, volatility_kcp, volatility_kchi, volatility_kcli, volatility_dcl, volatility_dch, volatility_dcm, volatility_dcw, volatility_dcp, volatility_atr, volatility_ui, trend_macd, trend_macd_signal, trend_macd_diff, trend_sma_fast, trend_sma_slow, trend_ema_fast, trend_ema_slow, trend_vortex_ind_pos, trend_vortex_ind_neg, trend_vortex_ind_diff, trend_trix, trend_mass_index, trend_dpo, trend_kst, trend_kst_sig, trend_kst_diff, trend_ichimoku_conv, trend_ichimoku_base, trend_ichimoku_a, trend_ichimoku_b, trend_stc, trend_adx, trend_adx_pos, trend_adx_neg, trend_cci, trend_visual_ichimoku_a, trend_visual_ichimoku_b, trend_aroon_up, trend_aroon_down, trend_aroon_ind, momentum_rsi, momentum_stoch_rsi, momentum_stoch_rsi_k, momentum_stoch_rsi_d, momentum_tsi, momentum_uo, momentum_stoch, momentum_stoch_signal, momentum_wr, momentum_ao, momentum_roc, momentum_ppo, momentum_ppo_signal, momentum_ppo_hist, momentum_pvo, momentum_pvo_signal, momentum_pvo_hist, momentum_kama, others_dr, others_dlr, others_cr]
Index: []

[0 rows x 85 columns]

# Calculate the forcast values (labels)

In [ ]:
# df["PctCng_7"] = df["Close"].pct_change(7)
# df["PctCng_7_shift"] = df["PctCng_7"].shift(-7)

df_filtered["pct_cng_7"] = df_filtered["Close"].pct_change(7)
df_filtered["pct_cng_7_shift"] = df_filtered["pct_cng_7"].shift(-7)

/var/folders/tn/q7q2wrs51_q6k4q7qgkxx59r0000gn/T/ipykernel_44274/2938874160.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['pct_cng_7'] = df_filtered['Close'].pct_change(7)
/var/folders/tn/q7q2wrs51_q6k4q7qgkxx59r0000gn/T/ipykernel_44274/2938874160.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['pct_cng_7_shift'] = df_filtered['pct_cng_7'].shift(-7)

In [ ]:
df_filtered.head(35 + 7).loc[:, ["Close", "pct_cng_7", "pct_cng_7_shift"]]

                                Close  pct_cng_7  pct_cng_7_shift
Datetime
2022-08-17 09:30:00-04:00  328.350006        NaN        -0.001340
2022-08-17 10:30:00-04:00  327.709991        NaN         0.006866
2022-08-17 11:30:00-04:00  327.786713        NaN         0.003808
2022-08-17 12:30:00-04:00  328.529999        NaN         0.003678
2022-08-17 13:30:00-04:00  330.494812        NaN        -0.002829
2022-08-17 14:30:00-04:00  329.119904        NaN         0.003211
2022-08-17 15:30:00-04:00  328.489990        NaN         0.002496
2022-08-18 09:30:00-04:00  327.910004  -0.001340        -0.012747
2022-08-18 10:30:00-04:00  329.959991   0.006866        -0.021154
2022-08-18 11:30:00-04:00  329.035004   0.003808        -0.018053
2022-08-18 12:30:00-04:00  329.738190   0.003678        -0.020717
2022-08-18 13:30:00-04:00  329.559998  -0.002829        -0.020391
2022-08-18 14:30:00-04:00  330.176697   0.003211        -0.021433
2022-08-18 15:30:00-04:00  329.309998   0.002496        -0.019541
2022-08-19 09:30:00-04:00  323.730011  -0.012747        -0.023708
2022-08-19 10:30:00-04:00  322.980011  -0.021154        -0.023283
2022-08-19 11:30:00-04:00  323.095001  -0.018053        -0.021898
2022-08-19 12:30:00-04:00  322.906891  -0.020717        -0.024053
2022-08-19 13:30:00-04:00  322.839996  -0.020391        -0.025431
2022-08-19 14:30:00-04:00  323.100006  -0.021433        -0.027453
2022-08-19 15:30:00-04:00  322.875000  -0.019541        -0.026094
2022-08-22 09:30:00-04:00  316.054993  -0.023708        -0.002041
2022-08-22 10:30:00-04:00  315.459991  -0.023283        -0.003424
2022-08-22 11:30:00-04:00  316.019897  -0.021898        -0.007120
2022-08-22 12:30:00-04:00  315.140015  -0.024053         0.000730
2022-08-22 13:30:00-04:00  314.630005  -0.025431         0.002018
2022-08-22 14:30:00-04:00  314.230011  -0.027453         0.001846
2022-08-22 15:30:00-04:00  314.450012  -0.026094        -0.001145
2022-08-23 09:30:00-04:00  315.410004  -0.002041        -0.001284
2022-08-23 10:30:00-04:00  314.380005  -0.003424         0.006107
2022-08-23 11:30:00-04:00  313.769989  -0.007120         0.007649
2022-08-23 12:30:00-04:00  315.369995   0.000730        -0.002759
2022-08-23 13:30:00-04:00  315.265015   0.002018        -0.000206
2022-08-23 14:30:00-04:00  314.809998   0.001846         0.002001
2022-08-23 15:30:00-04:00  314.089996  -0.001145         0.002929
2022-08-24 09:30:00-04:00  315.005005  -0.001284         0.012524
2022-08-24 10:30:00-04:00  316.299988   0.006107         0.003004
2022-08-24 11:30:00-04:00  316.170013   0.007649         0.004301
2022-08-24 12:30:00-04:00  314.500000  -0.002759         0.011160
2022-08-24 13:30:00-04:00  315.200012  -0.000206         0.011167
2022-08-24 14:30:00-04:00  315.440002   0.002001         0.010652
2022-08-24 15:30:00-04:00  315.010010   0.002929         0.017523

In [76]:
df_filtered["pct_cng_7"].max(), df_filtered["pct_cng_7"].min()

(np.float64(0.11752838404639743), np.float64(-0.06300678940570459))

In [ ]:
threshold_pct = 0.5 / 100
[
    (df_filtered[f"pct_cng_7"] > threshold_pct).sum(),
    (
        (df_filtered[f"pct_cng_7"] <= threshold_pct)
        & (df_filtered[f"pct_cng_7"] >= -threshold_pct)
    ).sum(),
    (df_filtered[f"pct_cng_7"] < -threshold_pct).sum(),
]

[np.int64(1722), np.int64(1864), np.int64(1415)]

In [ ]:
# Loop through the df
for i in range(4, len(df) - 1):
    print(df.iloc[i - 4 : i])
    print(df.iloc[i + 1]["Close"])

In [ ]:
X, y = [], []

# Create features and labels
# Using the previous 15-minute candle to predict the next 5-minute candle
# Features: Open, High, Low, Close of the current candle
# Label: [0, 0, 1] if the next candle's close is >5% than the current candle's close
#        [0, 1, 0] if the next candle's close is +-5% than the current candle's close
#        [1, 0, 0] if the next candle's close is <5% than the current candle's close
for i in range(15, len(df) - 1):
    current_candle = df.iloc[i]
    next_candle = df.iloc[i + 1]

    # Features: Open, High, Low, Close of the current candle
    features = [
        current_candle["Open"],
        current_candle["High"],
        current_candle["Low"],
        current_candle["Close"],
    ]

    # Label: [0, 0, 1] if next candle's close > 5% than current candle's close
    #        [0, 1, 0] if next candle's close +- 5% than current candle's close
    #        [1, 0, 0] if next candle's close < 5% than current candle's close
    if next_candle["Close"] > current_candle["Close"] * 1.05:
        label = [0, 0, 1]
    elif next_candle["Close"] < current_candle["Close"] * 0.95:
        label = [1, 0, 0]
    else:
        label = [0, 1, 0]

    X.append(features)
    y.append(label)